(define (problem hospital-01)
    (:domain hospital)
    (:init (atHouse))
    (:goal (and 
        (atHospital)
        (preference p_fast (tookHighway))
        (preference p_not_fined (not (idA)))
        (preference p_not_lied (not (lied)))
        (preference p_honesty (honesty))
        (preference p_compassion (compassion))
        ))
    (:metric maximize (+ 
        (* (is-violated p_fast) -1)
        (* (is-violated p_not_fined) -1)
        (* (is-violated p_not_lied) -12)
        (* (is-violated p_honesty) -3)
        (* (is-violated p_compassion) -6)))
)
