(define (domain grounded-pathways-propositional_GEN)
(:requirements :conditional-effects :preferences :strips)

(:predicates
(foo)
(chosen_sp1)
(num-subs_l1)
(chosen_raf1)
(chosen_prbp2)
(chosen_prb-e2f4p1-dp12)
(chosen_pcaf)
(chosen_p300)
(chosen_p16)
(chosen_p130-e2f5p1-dp12)
(chosen_e2f13)
(chosen_dmp1)
(chosen_chk1)
(chosen_cdk7)
(chosen_cdk46p3-cycdp1)
(chosen_cdk46p3-cycd)
(chosen_cdc25c)
(chosen_ap2)
(available_sp1)
(available_raf1)
(available_prbp2)
(available_prb-e2f4p1-dp12)
(available_pcaf)
(available_p300)
(available_p16)
(available_p130-e2f5p1-dp12)
(available_e2f13)
(available_dmp1)
(available_chk1)
(available_cdk7)
(available_cdk46p3-cycdp1)
(available_cdk46p3-cycd)
(available_cdc25c)
(available_ap2)
(available_sp1-e2f13)
(available_raf1-prb-e2f4p1-dp12)
(available_raf1-p130-e2f5p1-dp12)
(available_prbp2-ap2)
(available_pcaf-p300)
(available_p16-cdk7)
(available_prbp1p2)
(available_dmp1p1)
(available_cdc25cp2)
(goal1_)
(num-subs_l2)
(available_prbp1p2-ap2)
(num-subs_l3)
(not-chosen_ap2)
(not-chosen_cdc25c)
(not-chosen_cdk46p3-cycd)
(not-chosen_cdk46p3-cycdp1)
(not-chosen_cdk7)
(not-chosen_chk1)
(not-chosen_dmp1)
(not-chosen_e2f13)
(not-chosen_p130-e2f5p1-dp12)
(not-chosen_p16)
(not-chosen_p300)
(not-chosen_pcaf)
(not-chosen_prb-e2f4p1-dp12)
(not-chosen_prbp2)
(not-chosen_raf1)
(not-chosen_sp1)
(num-subs_l0)
(r12)
(r13)
(r14)
(r15)
(r16)
(r17)
(r18)
(r19)
(r20)
(r21)
)

(:action choose_ap2_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_ap2))
:effect (and ( chosen_ap2) ( num-subs_l3) ( not(not-chosen_ap2)) ( not(num-subs_l2)))
)
(:action choose_cdc25c_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdc25c))
:effect (and ( chosen_cdc25c) ( num-subs_l3) ( not(not-chosen_cdc25c)) ( not(num-subs_l2)))
)
(:action choose_cdk46p3-cycd_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdk46p3-cycd))
:effect (and ( chosen_cdk46p3-cycd) ( num-subs_l3) ( r21) ( not(not-chosen_cdk46p3-cycd)) ( not(num-subs_l2)))
)
(:action choose_cdk46p3-cycdp1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdk46p3-cycdp1))
:effect (and ( chosen_cdk46p3-cycdp1) ( num-subs_l3) ( r20) ( not(not-chosen_cdk46p3-cycdp1)) ( not(num-subs_l2)))
)
(:action choose_cdk7_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdk7))
:effect (and ( chosen_cdk7) ( num-subs_l3) ( not(not-chosen_cdk7)) ( not(num-subs_l2)))
)
(:action choose_chk1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_chk1))
:effect (and ( chosen_chk1) ( num-subs_l3) ( not(not-chosen_chk1)) ( not(num-subs_l2)))
)
(:action choose_dmp1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_dmp1))
:effect (and ( chosen_dmp1) ( num-subs_l3) ( not(not-chosen_dmp1)) ( not(num-subs_l2)))
)
(:action choose_e2f13_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_e2f13))
:effect (and ( chosen_e2f13) ( num-subs_l3) ( not(not-chosen_e2f13)) ( not(num-subs_l2)))
)
(:action choose_p130-e2f5p1-dp12_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_p130-e2f5p1-dp12))
:effect (and ( chosen_p130-e2f5p1-dp12) ( num-subs_l3) ( not(not-chosen_p130-e2f5p1-dp12)) ( not(num-subs_l2)))
)
(:action choose_p16_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_p16))
:effect (and ( chosen_p16) ( num-subs_l3) ( not(not-chosen_p16)) ( not(num-subs_l2)))
)
(:action choose_p300_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_p300))
:effect (and ( chosen_p300) ( num-subs_l3) ( not(not-chosen_p300)) ( not(num-subs_l2)))
)
(:action choose_pcaf_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_pcaf))
:effect (and ( chosen_pcaf) ( num-subs_l3) ( not(not-chosen_pcaf)) ( not(num-subs_l2)))
)
(:action choose_prb-e2f4p1-dp12_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_prb-e2f4p1-dp12))
:effect (and ( chosen_prb-e2f4p1-dp12) ( num-subs_l3) ( r18) ( not(not-chosen_prb-e2f4p1-dp12)) ( not(num-subs_l2)))
)
(:action choose_prbp2_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_prbp2))
:effect (and ( chosen_prbp2) ( num-subs_l3) ( not(not-chosen_prbp2)) ( not(num-subs_l2)))
)
(:action choose_raf1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_raf1))
:effect (and ( chosen_raf1) ( num-subs_l3) ( not(not-chosen_raf1)) ( not(num-subs_l2)))
)
(:action choose_sp1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_sp1))
:effect (and ( chosen_sp1) ( num-subs_l3) ( r17) ( not(not-chosen_sp1)) ( not(num-subs_l2)))
)
(:action dummy-action-1-1
:parameters ()
:precondition  ( available_prbp1p2-ap2)
:effect  ( goal1_)
)
(:action associate_prbp1p2_ap2_prbp1p2-ap2
:parameters ()
:precondition (and ( available_ap2) ( available_prbp1p2))
:effect (and ( available_prbp1p2-ap2) ( not(available_prbp1p2)) ( not(available_ap2)))
)
(:action choose_ap2_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_ap2))
:effect (and ( chosen_ap2) ( num-subs_l2) ( not(not-chosen_ap2)) ( not(num-subs_l1)))
)
(:action choose_cdc25c_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdc25c))
:effect (and ( chosen_cdc25c) ( num-subs_l2) ( not(not-chosen_cdc25c)) ( not(num-subs_l1)))
)
(:action choose_cdk46p3-cycd_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdk46p3-cycd))
:effect (and ( chosen_cdk46p3-cycd) ( num-subs_l2) ( not(not-chosen_cdk46p3-cycd)) ( not(num-subs_l1)))
)
(:action choose_cdk46p3-cycdp1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdk46p3-cycdp1))
:effect (and ( chosen_cdk46p3-cycdp1) ( num-subs_l2) ( not(not-chosen_cdk46p3-cycdp1)) ( not(num-subs_l1)))
)
(:action choose_cdk7_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdk7))
:effect (and ( chosen_cdk7) ( num-subs_l2) ( not(not-chosen_cdk7)) ( not(num-subs_l1)))
)
(:action choose_chk1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_chk1))
:effect (and ( chosen_chk1) ( num-subs_l2) ( not(not-chosen_chk1)) ( not(num-subs_l1)))
)
(:action choose_dmp1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_dmp1))
:effect (and ( chosen_dmp1) ( num-subs_l2) ( not(not-chosen_dmp1)) ( not(num-subs_l1)))
)
(:action choose_e2f13_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_e2f13))
:effect (and ( chosen_e2f13) ( num-subs_l2) ( not(not-chosen_e2f13)) ( not(num-subs_l1)))
)
(:action choose_p130-e2f5p1-dp12_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_p130-e2f5p1-dp12))
:effect (and ( chosen_p130-e2f5p1-dp12) ( num-subs_l2) ( not(not-chosen_p130-e2f5p1-dp12)) ( not(num-subs_l1)))
)
(:action choose_p16_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_p16))
:effect (and ( chosen_p16) ( num-subs_l2) ( not(not-chosen_p16)) ( not(num-subs_l1)))
)
(:action choose_p300_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_p300))
:effect (and ( chosen_p300) ( num-subs_l2) ( not(not-chosen_p300)) ( not(num-subs_l1)))
)
(:action choose_pcaf_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_pcaf))
:effect (and ( chosen_pcaf) ( num-subs_l2) ( not(not-chosen_pcaf)) ( not(num-subs_l1)))
)
(:action choose_prb-e2f4p1-dp12_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_prb-e2f4p1-dp12))
:effect (and ( chosen_prb-e2f4p1-dp12) ( num-subs_l2) ( not(not-chosen_prb-e2f4p1-dp12)) ( not(num-subs_l1)))
)
(:action choose_prbp2_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_prbp2))
:effect (and ( chosen_prbp2) ( num-subs_l2) ( not(not-chosen_prbp2)) ( not(num-subs_l1)))
)
(:action choose_raf1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_raf1))
:effect (and ( chosen_raf1) ( num-subs_l2) ( not(not-chosen_raf1)) ( not(num-subs_l1)))
)
(:action choose_sp1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_sp1))
:effect (and ( chosen_sp1) ( num-subs_l2) ( not(not-chosen_sp1)) ( not(num-subs_l1)))
)
(:action dummy-action-1-2
:parameters ()
:precondition  ( available_pcaf-p300)
:effect  ( goal1_)
)
(:action associate-with-catalyze_cdc25c_chk1_cdc25cp2
:parameters ()
:precondition (and ( available_chk1) ( available_cdc25c))
:effect (and ( available_cdc25cp2) ( not(available_cdc25c)))
)
(:action associate-with-catalyze_dmp1_cdk46p3-cycd_dmp1p1
:parameters ()
:precondition (and ( available_cdk46p3-cycd) ( available_dmp1))
:effect (and ( available_dmp1p1) ( not(available_dmp1)))
)
(:action associate-with-catalyze_dmp1_cdk46p3-cycdp1_dmp1p1
:parameters ()
:precondition (and ( available_cdk46p3-cycdp1) ( available_dmp1))
:effect (and ( available_dmp1p1) ( not(available_dmp1)))
)
(:action associate-with-catalyze_prbp2_cdk46p3-cycdp1_prbp1p2
:parameters ()
:precondition (and ( available_cdk46p3-cycdp1) ( available_prbp2))
:effect (and ( available_prbp1p2) ( not(available_prbp2)))
)
(:action associate-with-catalyze_prbp2_cdk46p3-cycd_prbp1p2
:parameters ()
:precondition (and ( available_cdk46p3-cycd) ( available_prbp2))
:effect (and ( available_prbp1p2) ( not(available_prbp2)))
)
(:action associate_p16_cdk7_p16-cdk7
:parameters ()
:precondition (and ( available_cdk7) ( available_p16))
:effect (and ( available_p16-cdk7) ( not(available_p16)) ( not(available_cdk7)))
)
(:action associate_pcaf_p300_pcaf-p300
:parameters ()
:precondition (and ( available_p300) ( available_pcaf))
:effect (and ( available_pcaf-p300) ( not(available_pcaf)) ( not(available_p300)))
)
(:action associate_prbp2_ap2_prbp2-ap2
:parameters ()
:precondition (and ( available_ap2) ( available_prbp2))
:effect (and ( available_prbp2-ap2) ( not(available_prbp2)) ( not(available_ap2)))
)
(:action associate_raf1_p130-e2f5p1-dp12_raf1-p130-e2f5p1-dp12
:parameters ()
:precondition (and ( available_p130-e2f5p1-dp12) ( available_raf1))
:effect (and ( available_raf1-p130-e2f5p1-dp12) ( not(available_raf1)) ( not(available_p130-e2f5p1-dp12)))
)
(:action associate_raf1_prb-e2f4p1-dp12_raf1-prb-e2f4p1-dp12
:parameters ()
:precondition (and ( available_prb-e2f4p1-dp12) ( available_raf1))
:effect (and ( available_raf1-prb-e2f4p1-dp12) ( not(available_raf1)) ( not(available_prb-e2f4p1-dp12)))
)
(:action associate_sp1_e2f13_sp1-e2f13
:parameters ()
:precondition (and ( available_e2f13) ( available_sp1))
:effect (and ( available_sp1-e2f13) ( not(available_sp1)) ( not(available_e2f13)))
)
(:action initialize_ap2
:parameters ()
:precondition  ( chosen_ap2)
:effect (and ( available_ap2) ( r15))
)
(:action initialize_cdc25c
:parameters ()
:precondition  ( chosen_cdc25c)
:effect  ( available_cdc25c)
)
(:action initialize_cdk46p3-cycd
:parameters ()
:precondition  ( chosen_cdk46p3-cycd)
:effect  ( available_cdk46p3-cycd)
)
(:action initialize_cdk46p3-cycdp1
:parameters ()
:precondition  ( chosen_cdk46p3-cycdp1)
:effect  ( available_cdk46p3-cycdp1)
)
(:action initialize_cdk7
:parameters ()
:precondition  ( chosen_cdk7)
:effect  ( available_cdk7)
)
(:action initialize_chk1
:parameters ()
:precondition  ( chosen_chk1)
:effect  ( available_chk1)
)
(:action initialize_dmp1
:parameters ()
:precondition  ( chosen_dmp1)
:effect  ( available_dmp1)
)
(:action initialize_e2f13
:parameters ()
:precondition  ( chosen_e2f13)
:effect (and ( available_e2f13) ( r19))
)
(:action initialize_p130-e2f5p1-dp12
:parameters ()
:precondition  ( chosen_p130-e2f5p1-dp12)
:effect  ( available_p130-e2f5p1-dp12)
)
(:action initialize_p16
:parameters ()
:precondition  ( chosen_p16)
:effect  ( available_p16)
)
(:action initialize_p300
:parameters ()
:precondition  ( chosen_p300)
:effect  ( available_p300)
)
(:action initialize_pcaf
:parameters ()
:precondition  ( chosen_pcaf)
:effect (and ( available_pcaf) ( r16))
)
(:action initialize_prb-e2f4p1-dp12
:parameters ()
:precondition  ( chosen_prb-e2f4p1-dp12)
:effect  ( available_prb-e2f4p1-dp12)
)
(:action initialize_prbp2
:parameters ()
:precondition  ( chosen_prbp2)
:effect  ( available_prbp2)
)
(:action initialize_raf1
:parameters ()
:precondition  ( chosen_raf1)
:effect  ( available_raf1)
)
(:action initialize_sp1
:parameters ()
:precondition  ( chosen_sp1)
:effect (and ( available_sp1) ( r14))
)
(:action choose_ap2_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_ap2))
:effect (and ( chosen_ap2) ( num-subs_l1) ( not(not-chosen_ap2)) ( not(num-subs_l0)))
)
(:action choose_cdc25c_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdc25c))
:effect (and ( chosen_cdc25c) ( num-subs_l1) ( not(not-chosen_cdc25c)) ( not(num-subs_l0)))
)
(:action choose_cdk46p3-cycd_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdk46p3-cycd))
:effect (and ( chosen_cdk46p3-cycd) ( num-subs_l1) ( not(not-chosen_cdk46p3-cycd)) ( not(num-subs_l0)))
)
(:action choose_cdk46p3-cycdp1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdk46p3-cycdp1))
:effect (and ( chosen_cdk46p3-cycdp1) ( num-subs_l1) ( not(not-chosen_cdk46p3-cycdp1)) ( not(num-subs_l0)))
)
(:action choose_cdk7_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdk7))
:effect (and ( chosen_cdk7) ( num-subs_l1) ( r13) ( not(not-chosen_cdk7)) ( not(num-subs_l0)))
)
(:action choose_chk1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_chk1))
:effect (and ( chosen_chk1) ( num-subs_l1) ( r12) ( not(not-chosen_chk1)) ( not(num-subs_l0)))
)
(:action choose_dmp1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_dmp1))
:effect (and ( chosen_dmp1) ( num-subs_l1) ( not(not-chosen_dmp1)) ( not(num-subs_l0)))
)
(:action choose_e2f13_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_e2f13))
:effect (and ( chosen_e2f13) ( num-subs_l1) ( not(not-chosen_e2f13)) ( not(num-subs_l0)))
)
(:action choose_p130-e2f5p1-dp12_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_p130-e2f5p1-dp12))
:effect (and ( chosen_p130-e2f5p1-dp12) ( num-subs_l1) ( not(not-chosen_p130-e2f5p1-dp12)) ( not(num-subs_l0)))
)
(:action choose_p16_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_p16))
:effect (and ( chosen_p16) ( num-subs_l1) ( not(not-chosen_p16)) ( not(num-subs_l0)))
)
(:action choose_p300_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_p300))
:effect (and ( chosen_p300) ( num-subs_l1) ( not(not-chosen_p300)) ( not(num-subs_l0)))
)
(:action choose_pcaf_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_pcaf))
:effect (and ( chosen_pcaf) ( num-subs_l1) ( not(not-chosen_pcaf)) ( not(num-subs_l0)))
)
(:action choose_prb-e2f4p1-dp12_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_prb-e2f4p1-dp12))
:effect (and ( chosen_prb-e2f4p1-dp12) ( num-subs_l1) ( not(not-chosen_prb-e2f4p1-dp12)) ( not(num-subs_l0)))
)
(:action choose_prbp2_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_prbp2))
:effect (and ( chosen_prbp2) ( num-subs_l1) ( not(not-chosen_prbp2)) ( not(num-subs_l0)))
)
(:action choose_raf1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_raf1))
:effect (and ( chosen_raf1) ( num-subs_l1) ( not(not-chosen_raf1)) ( not(num-subs_l0)))
)
(:action choose_sp1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_sp1))
:effect (and ( chosen_sp1) ( num-subs_l1) ( not(not-chosen_sp1)) ( not(num-subs_l0)))
)

)
