#!/bin/bash

# export CPLEX="/Applications/CPLEX_Studio1210/cplex/lib/x86-64_osx/static_pic/libcplex.a"
# export ILOCPLEX="/Applications/CPLEX_Studio1210/cplex/lib/x86-64_osx/static_pic/libilocplex.a"
# export CONCERT="/Applications/CPLEX_Studio1210/concert/lib/x86-64_osx/static_pic/libconcert.a"
# export CPLEX_INCLUDES="/Applications/CPLEX_Studio1210/cplex/include"
# export CONCERT_INCLUDES="/Applications/CPLEX_Studio1210/concert/include"

export CPLEX="/Applications/CPLEX_Studio1210/opl/lib/x86-64_osx/static_pic/libcplex.a"

if [ ! -e "$CPLEX" ]; then
    echo "$CPLEX is not the libcplex.a library file"
    exit 1
fi

export ILOCPLEX="/Applications/CPLEX_Studio1210/opl/lib/x86-64_osx/static_pic/libilocplex.a"

if [ ! -e "$ILOCPLEX" ]; then
    echo "$ILOCPLEX is not the libilocplex.a library file"
    exit 1
fi

export CONCERT="/Applications/CPLEX_Studio1210/opl/lib/x86-64_osx/static_pic/libconcert.a"

if [ ! -e "$CONCERT" ]; then
    echo "$CONCERT is not the libconcert.a library file"
    exit 1
fi

export CPLEX_INCLUDES="/Applications/CPLEX_Studio1210/cplex/include"

if [ ! -e "$CPLEX_INCLUDES/ilcplex/ilocplex.h" ]; then
    echo "$CPLEX_INCLUDES does not point to a path containing ilcplex/ilocplex.h"
    exit 1
fi


export CONCERT_INCLUDES="/Applications/CPLEX_Studio1210/opl/include"

if [ ! -e "$CONCERT_INCLUDES/ilconcert/iloenv.h" ]; then
    echo "$CONCERT_INCLUDES does not point to a path containing ilconcert/iloenv.h"
    exit 1
fi


cd compile
cmake -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_BUILD_TYPE=Release -DCPLEX="$CPLEX" -DILOCPLEX="$ILOCPLEX" -DCONCERT="$CONCERT" -DCPLEX_INCLUDES="$CPLEX_INCLUDES" -DCONCERT_INCLUDES="$CONCERT_INCLUDES"  ../src

make lprpgp-cplex