data.action.o: data.action.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.numericalCondition.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h
data.actionDescription.o: data.actionDescription.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.numericalCondition.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.code.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h
data.code.o: data.code.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.code.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.factGroup.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.mergedPredicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h
data.domain.o: data.domain.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.parser.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.scanner.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.factGroup.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.code.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.mergedPredicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.partPredicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.factMap.h
data.exploreStep.o: data.exploreStep.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.numericalCondition.h
data.fact.o: data.fact.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h
data.factGroup.o: data.factGroup.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.mergedPredicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.factGroup.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.partPredicate.h
data.formula.o: data.formula.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.numericalCondition.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h
data.function.o: data.function.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h
data.instantiation.o: data.instantiation.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h
data.mergedPredicate.o: data.mergedPredicate.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.partPredicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.mergedPredicate.h
data.numericalCondition.o: data.numericalCondition.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.numericalCondition.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h
data.object.o: data.object.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h
data.partPredicate.o: data.partPredicate.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.partPredicate.h
data.predicate.o: data.predicate.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h
data.symbolicFact.o: data.symbolicFact.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.function.h
data.tree.o: data.tree.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.factMap.h
data.types.o: data.types.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.types.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h
lisp.entity.o: lisp.entity.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h
lisp.parser.o: lisp.parser.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.parser.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.scanner.h
lisp.scanner.o: lisp.scanner.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.scanner.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h
mips.o: mips.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h
out.factMap.o: out.factMap.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.object.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.code.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.factGroup.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.exploreStep.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.actionDescription.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.group.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/lisp.entity.h
out.group.o: out.group.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.group.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.operator.h
out.operator.o: out.operator.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/data.tree.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/out.group.h
util.bitarray.o: util.bitarray.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.bitarray.h
util.options.o: util.options.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h
util.prioqueue.o: util.prioqueue.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.prioqueue.h
util.tools.o: util.tools.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.rational.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/ground/include/util.tools.h
