#!/bin/bash

echo removing existing solution file 
rm -f $2.soln
echo "eliminating -number"
sed s/"- number"//g $1 > temporary
echo "now instantiating"
ground/ground temporary $2
echo "starting planner"
./bdd-solver domain.pddl problem.pddl 
out=$?
echo "program output:"
echo $out
if [ $out = 0 ]; then
  sed s/"\."/"\ /"g  simple-solution > $3
else
  echo "possibly sub-optimal solution found!"
fi
