bdd.arithmetics.o: bdd.arithmetics.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h
bdd.bdda.o: bdd.bdda.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.heuristic.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pdb.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h
bdd.bfs.o: bdd.bfs.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h
bdd.bnb.o: bdd.bnb.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.heuristic.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pdb.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h
bdd.dijkstra.o: bdd.dijkstra.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.heuristic.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pdb.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h
bdd.search.o: bdd.search.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.heuristic.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pdb.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h
bdd.solution.o: bdd.solution.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.heuristic.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pdb.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.pattern.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h
data.action.o: data.action.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.symbolicFact.h
data.domain.o: data.domain.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.parser.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.scanner.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h
data.formula.o: data.formula.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h
data.instantiation.o: data.instantiation.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.fact.h
data.predicate.o: data.predicate.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h
data.symbolicFact.o: data.symbolicFact.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.symbolicFact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h
lisp.entity.o: lisp.entity.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h
lisp.parser.o: lisp.parser.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.entity.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.parser.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.scanner.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h
lisp.scanner.o: lisp.scanner.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/lisp.scanner.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h
mips.o: mips.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h
out.factMap.o: out.factMap.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.fact.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.predicate.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.domain.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.action.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.instantiation.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/data.formula.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.bfs.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.arithmetics.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.group.h
out.group.o: out.group.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.group.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h
out.operator.o: out.operator.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h
single.search.o: single.search.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.queue.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.operator.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.search.h
single.state.o: single.state.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/single.state.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/out.factMap.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/bdd.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/fdd.h
util.bitarray.o: util.bitarray.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.bitarray.h
util.options.o: util.options.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.options.h \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h
util.ourparser.o: util.ourparser.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.ourparser.h
util.prioqueue.o: util.prioqueue.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.prioqueue.h
util.tools.o: util.tools.cc \
  /Users/martinjedwabny/Desktop/pddl/planners/gamer/include/util.tools.h
