(define (domain grounded-pathways-propositional_GEN)
(:requirements :conditional-effects :preferences :strips)

(:predicates
(foo)
(chosen_wee1)
(num-subs_l1)
(chosen_sp1)
(chosen_rpa)
(chosen_prbp2)
(chosen_prbp1-e2f4p1-dp12)
(chosen_prb-e2f4p1-dp12)
(chosen_pcna)
(chosen_m1433)
(chosen_hdac1-p130-e2f4p1-dp12)
(chosen_hdac1)
(chosen_gp)
(chosen_ge2)
(chosen_e2f6-dp12p1)
(chosen_e2f4-dp12p1)
(chosen_e2f13)
(chosen_dmp1)
(chosen_c-tak1)
(chosen_cebp)
(chosen_cdk2p1)
(chosen_cdk2)
(chosen_cdc25c)
(chosen_c-abl)
(available_wee1)
(available_sp1)
(available_rpa)
(available_prbp2)
(available_prbp1-e2f4p1-dp12)
(available_prb-e2f4p1-dp12)
(available_pcna)
(available_m1433)
(available_hdac1-p130-e2f4p1-dp12)
(available_hdac1)
(available_gp)
(available_ge2)
(available_e2f6-dp12p1)
(available_e2f4-dp12p1)
(available_e2f13)
(available_dmp1)
(available_c-tak1)
(available_cebp)
(available_cdk2p1)
(available_cdk2)
(available_cdc25c)
(available_c-abl)
(available_sp1-gp)
(available_sp1-e2f13)
(available_sp1-e2f13-gp)
(available_prbp1-e2f4p1-dp12-ge2)
(available_prb-e2f4p1-dp12-ge2)
(available_hdac1-prb-e2f4p1-dp12)
(available_hdac1-p130-e2f4p1-dp12-ge2)
(available_e2f6-dp12p1-ge2)
(available_cebp-prbp2)
(available_cebp-gp)
(available_c-abl-prbp2)
(available_cdc25cp2)
(available_pol)
(available_p19arf)
(available_p107p1)
(available_p107)
(available_cycep1)
(available_cyce)
(available_cycdp1)
(available_cycd)
(available_cyca)
(available_c-myc)
(available_p)
(goal1_)
(goal2_)
(goal4_)
(num-subs_l2)
(available_sp1-p107)
(available_sp1-p107p1)
(available_sp1-p107p1-gp)
(available_sp1-p107-gp)
(available_rpa-cyca)
(available_pcna-cycd)
(available_pcna-cycdp1)
(available_p107-e2f4-dp12p1)
(available_p107-e2f4-dp12p1-ge2)
(available_m1433-cdc25cp2)
(available_hdac1-p107-e2f4-dp12p1)
(available_dmp1-cycdp1)
(available_dmp1-cycd)
(available_cebp-prbp2-gp)
(available_cdk2p1-cycep1)
(available_cdk2p1-cyce)
(available_cdk2p1-cyca)
(available_cdk2-cycep1)
(available_cdk2-cyce)
(available_cdk2-cyca)
(goal3_)
(num-subs_l3)
(available_cdk2p1-cyca-e2f13)
(available_cdk2-cyca-e2f13)
(not-chosen_c-abl)
(not-chosen_cdc25c)
(not-chosen_cdk2)
(not-chosen_cdk2p1)
(not-chosen_cebp)
(not-chosen_c-tak1)
(not-chosen_dmp1)
(not-chosen_e2f13)
(not-chosen_e2f4-dp12p1)
(not-chosen_e2f6-dp12p1)
(not-chosen_ge2)
(not-chosen_gp)
(not-chosen_hdac1)
(not-chosen_hdac1-p130-e2f4p1-dp12)
(not-chosen_m1433)
(not-chosen_pcna)
(not-chosen_prb-e2f4p1-dp12)
(not-chosen_prbp1-e2f4p1-dp12)
(not-chosen_prbp2)
(not-chosen_rpa)
(not-chosen_sp1)
(not-chosen_wee1)
(num-subs_l0)
(r5)
(r6)
(r7)
)

(:action dummy-action-3-1
:parameters ()
:precondition  ( available_cdk2-cyca-e2f13)
:effect  ( goal3_)
)
(:action associate_cdk2-cyca_e2f13_cdk2-cyca-e2f13
:parameters ()
:precondition (and ( available_e2f13) ( available_cdk2-cyca))
:effect (and ( available_cdk2-cyca-e2f13) ( not(available_cdk2-cyca)) ( not(available_e2f13)))
)
(:action associate_cdk2p1-cyca_e2f13_cdk2p1-cyca-e2f13
:parameters ()
:precondition (and ( available_e2f13) ( available_cdk2p1-cyca))
:effect (and ( available_cdk2p1-cyca-e2f13) ( not(available_cdk2p1-cyca)) ( not(available_e2f13)))
)
(:action choose_c-abl_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_c-abl))
:effect (and ( chosen_c-abl) ( num-subs_l3) ( not(not-chosen_c-abl)) ( not(num-subs_l2)))
)
(:action choose_cdc25c_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdc25c))
:effect (and ( chosen_cdc25c) ( num-subs_l3) ( not(not-chosen_cdc25c)) ( not(num-subs_l2)))
)
(:action choose_cdk2_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdk2))
:effect (and ( chosen_cdk2) ( num-subs_l3) ( not(not-chosen_cdk2)) ( not(num-subs_l2)))
)
(:action choose_cdk2p1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cdk2p1))
:effect (and ( chosen_cdk2p1) ( num-subs_l3) ( not(not-chosen_cdk2p1)) ( not(num-subs_l2)))
)
(:action choose_cebp_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_cebp))
:effect (and ( chosen_cebp) ( num-subs_l3) ( not(not-chosen_cebp)) ( not(num-subs_l2)))
)
(:action choose_c-tak1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_c-tak1))
:effect (and ( chosen_c-tak1) ( num-subs_l3) ( not(not-chosen_c-tak1)) ( not(num-subs_l2)))
)
(:action choose_dmp1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_dmp1))
:effect (and ( chosen_dmp1) ( num-subs_l3) ( not(not-chosen_dmp1)) ( not(num-subs_l2)))
)
(:action choose_e2f13_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_e2f13))
:effect (and ( chosen_e2f13) ( num-subs_l3) ( not(not-chosen_e2f13)) ( not(num-subs_l2)))
)
(:action choose_e2f4-dp12p1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_e2f4-dp12p1))
:effect (and ( chosen_e2f4-dp12p1) ( num-subs_l3) ( not(not-chosen_e2f4-dp12p1)) ( not(num-subs_l2)))
)
(:action choose_e2f6-dp12p1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_e2f6-dp12p1))
:effect (and ( chosen_e2f6-dp12p1) ( num-subs_l3) ( not(not-chosen_e2f6-dp12p1)) ( not(num-subs_l2)))
)
(:action choose_ge2_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_ge2))
:effect (and ( chosen_ge2) ( num-subs_l3) ( not(not-chosen_ge2)) ( not(num-subs_l2)))
)
(:action choose_gp_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_gp))
:effect (and ( chosen_gp) ( num-subs_l3) ( not(not-chosen_gp)) ( not(num-subs_l2)))
)
(:action choose_hdac1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_hdac1))
:effect (and ( chosen_hdac1) ( num-subs_l3) ( not(not-chosen_hdac1)) ( not(num-subs_l2)))
)
(:action choose_hdac1-p130-e2f4p1-dp12_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_hdac1-p130-e2f4p1-dp12))
:effect (and ( chosen_hdac1-p130-e2f4p1-dp12) ( num-subs_l3) ( not(not-chosen_hdac1-p130-e2f4p1-dp12)) ( not(num-subs_l2)))
)
(:action choose_m1433_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_m1433))
:effect (and ( chosen_m1433) ( num-subs_l3) ( not(not-chosen_m1433)) ( not(num-subs_l2)))
)
(:action choose_pcna_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_pcna))
:effect (and ( chosen_pcna) ( num-subs_l3) ( not(not-chosen_pcna)) ( not(num-subs_l2)))
)
(:action choose_prb-e2f4p1-dp12_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_prb-e2f4p1-dp12))
:effect (and ( chosen_prb-e2f4p1-dp12) ( num-subs_l3) ( not(not-chosen_prb-e2f4p1-dp12)) ( not(num-subs_l2)))
)
(:action choose_prbp1-e2f4p1-dp12_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_prbp1-e2f4p1-dp12))
:effect (and ( chosen_prbp1-e2f4p1-dp12) ( num-subs_l3) ( not(not-chosen_prbp1-e2f4p1-dp12)) ( not(num-subs_l2)))
)
(:action choose_prbp2_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_prbp2))
:effect (and ( chosen_prbp2) ( num-subs_l3) ( not(not-chosen_prbp2)) ( not(num-subs_l2)))
)
(:action choose_rpa_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_rpa))
:effect (and ( chosen_rpa) ( num-subs_l3) ( not(not-chosen_rpa)) ( not(num-subs_l2)))
)
(:action choose_sp1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_sp1))
:effect (and ( chosen_sp1) ( num-subs_l3) ( not(not-chosen_sp1)) ( not(num-subs_l2)))
)
(:action choose_wee1_l3_l2
:parameters ()
:precondition (and ( num-subs_l2) ( not-chosen_wee1))
:effect (and ( chosen_wee1) ( num-subs_l3) ( not(not-chosen_wee1)) ( not(num-subs_l2)))
)
(:action dummy-action-4-1
:parameters ()
:precondition  ( available_p107-e2f4-dp12p1-ge2)
:effect  ( goal4_)
)
(:action dummy-action-3-2
:parameters ()
:precondition  ( available_sp1-p107p1-gp)
:effect  ( goal3_)
)
(:action dummy-action-2-1
:parameters ()
:precondition  ( available_dmp1-cycdp1)
:effect  ( goal2_)
)
(:action dummy-action-1-1
:parameters ()
:precondition  ( available_cdk2p1-cyca)
:effect  ( goal1_)
)
(:action synthesize_cebp-prbp2-gp_p
:parameters ()
:precondition  ( available_cebp-prbp2-gp)
:effect  ( available_p)
)
(:action associate-with-catalyze_cdk2-cyca_wee1_cdk2p1-cyca
:parameters ()
:precondition (and ( available_wee1) ( available_cdk2-cyca))
:effect (and ( available_cdk2p1-cyca) ( not(available_cdk2-cyca)))
)
(:action associate_cdk2_cyca_cdk2-cyca
:parameters ()
:precondition (and ( available_cyca) ( available_cdk2))
:effect (and ( available_cdk2-cyca) ( not(available_cdk2)) ( not(available_cyca)))
)
(:action associate_cdk2_cyce_cdk2-cyce
:parameters ()
:precondition (and ( available_cyce) ( available_cdk2))
:effect (and ( available_cdk2-cyce) ( not(available_cdk2)) ( not(available_cyce)))
)
(:action associate_cdk2_cycep1_cdk2-cycep1
:parameters ()
:precondition (and ( available_cycep1) ( available_cdk2))
:effect (and ( available_cdk2-cycep1) ( not(available_cdk2)) ( not(available_cycep1)))
)
(:action associate_cdk2p1_cyca_cdk2p1-cyca
:parameters ()
:precondition (and ( available_cyca) ( available_cdk2p1))
:effect (and ( available_cdk2p1-cyca) ( not(available_cdk2p1)) ( not(available_cyca)))
)
(:action associate_cdk2p1_cyce_cdk2p1-cyce
:parameters ()
:precondition (and ( available_cyce) ( available_cdk2p1))
:effect (and ( available_cdk2p1-cyce) ( not(available_cdk2p1)) ( not(available_cyce)))
)
(:action associate_cdk2p1_cycep1_cdk2p1-cycep1
:parameters ()
:precondition (and ( available_cycep1) ( available_cdk2p1))
:effect (and ( available_cdk2p1-cycep1) ( not(available_cdk2p1)) ( not(available_cycep1)))
)
(:action associate_cebp-prbp2_gp_cebp-prbp2-gp
:parameters ()
:precondition (and ( available_gp) ( available_cebp-prbp2))
:effect (and ( available_cebp-prbp2-gp) ( not(available_cebp-prbp2)) ( not(available_gp)))
)
(:action associate_dmp1_cycd_dmp1-cycd
:parameters ()
:precondition (and ( available_cycd) ( available_dmp1))
:effect (and ( available_dmp1-cycd) ( not(available_dmp1)) ( not(available_cycd)))
)
(:action associate_dmp1_cycdp1_dmp1-cycdp1
:parameters ()
:precondition (and ( available_cycdp1) ( available_dmp1))
:effect (and ( available_dmp1-cycdp1) ( not(available_dmp1)) ( not(available_cycdp1)))
)
(:action associate_hdac1_p107-e2f4-dp12p1_hdac1-p107-e2f4-dp12p1
:parameters ()
:precondition (and ( available_p107-e2f4-dp12p1) ( available_hdac1))
:effect (and ( available_hdac1-p107-e2f4-dp12p1) ( not(available_hdac1)) ( not(available_p107-e2f4-dp12p1)))
)
(:action associate_m1433_cdc25cp2_m1433-cdc25cp2
:parameters ()
:precondition (and ( available_cdc25cp2) ( available_m1433))
:effect (and ( available_m1433-cdc25cp2) ( not(available_m1433)) ( not(available_cdc25cp2)))
)
(:action associate_p107-e2f4-dp12p1_ge2_p107-e2f4-dp12p1-ge2
:parameters ()
:precondition (and ( available_ge2) ( available_p107-e2f4-dp12p1))
:effect (and ( available_p107-e2f4-dp12p1-ge2) ( not(available_p107-e2f4-dp12p1)) ( not(available_ge2)))
)
(:action associate_p107_e2f4-dp12p1_p107-e2f4-dp12p1
:parameters ()
:precondition (and ( available_e2f4-dp12p1) ( available_p107))
:effect (and ( available_p107-e2f4-dp12p1) ( not(available_p107)) ( not(available_e2f4-dp12p1)))
)
(:action associate_pcna_cycdp1_pcna-cycdp1
:parameters ()
:precondition (and ( available_cycdp1) ( available_pcna))
:effect (and ( available_pcna-cycdp1) ( not(available_pcna)) ( not(available_cycdp1)))
)
(:action associate_pcna_cycd_pcna-cycd
:parameters ()
:precondition (and ( available_cycd) ( available_pcna))
:effect (and ( available_pcna-cycd) ( not(available_pcna)) ( not(available_cycd)))
)
(:action associate_rpa_cyca_rpa-cyca
:parameters ()
:precondition (and ( available_cyca) ( available_rpa))
:effect (and ( available_rpa-cyca) ( not(available_rpa)) ( not(available_cyca)))
)
(:action associate_sp1-p107_gp_sp1-p107-gp
:parameters ()
:precondition (and ( available_gp) ( available_sp1-p107))
:effect (and ( available_sp1-p107-gp) ( not(available_sp1-p107)) ( not(available_gp)))
)
(:action associate_sp1-p107p1_gp_sp1-p107p1-gp
:parameters ()
:precondition (and ( available_gp) ( available_sp1-p107p1))
:effect (and ( available_sp1-p107p1-gp) ( not(available_sp1-p107p1)) ( not(available_gp)))
)
(:action associate_sp1_p107p1_sp1-p107p1
:parameters ()
:precondition (and ( available_p107p1) ( available_sp1))
:effect (and ( available_sp1-p107p1) ( not(available_sp1)) ( not(available_p107p1)))
)
(:action associate_sp1_p107_sp1-p107
:parameters ()
:precondition (and ( available_p107) ( available_sp1))
:effect (and ( available_sp1-p107) ( not(available_sp1)) ( not(available_p107)))
)
(:action choose_c-abl_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_c-abl))
:effect (and ( chosen_c-abl) ( num-subs_l2) ( not(not-chosen_c-abl)) ( not(num-subs_l1)))
)
(:action choose_cdc25c_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdc25c))
:effect (and ( chosen_cdc25c) ( num-subs_l2) ( not(not-chosen_cdc25c)) ( not(num-subs_l1)))
)
(:action choose_cdk2_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdk2))
:effect (and ( chosen_cdk2) ( num-subs_l2) ( not(not-chosen_cdk2)) ( not(num-subs_l1)))
)
(:action choose_cdk2p1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cdk2p1))
:effect (and ( chosen_cdk2p1) ( num-subs_l2) ( not(not-chosen_cdk2p1)) ( not(num-subs_l1)))
)
(:action choose_cebp_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_cebp))
:effect (and ( chosen_cebp) ( num-subs_l2) ( not(not-chosen_cebp)) ( not(num-subs_l1)))
)
(:action choose_c-tak1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_c-tak1))
:effect (and ( chosen_c-tak1) ( num-subs_l2) ( not(not-chosen_c-tak1)) ( not(num-subs_l1)))
)
(:action choose_dmp1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_dmp1))
:effect (and ( chosen_dmp1) ( num-subs_l2) ( not(not-chosen_dmp1)) ( not(num-subs_l1)))
)
(:action choose_e2f13_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_e2f13))
:effect (and ( chosen_e2f13) ( num-subs_l2) ( not(not-chosen_e2f13)) ( not(num-subs_l1)))
)
(:action choose_e2f4-dp12p1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_e2f4-dp12p1))
:effect (and ( chosen_e2f4-dp12p1) ( num-subs_l2) ( not(not-chosen_e2f4-dp12p1)) ( not(num-subs_l1)))
)
(:action choose_e2f6-dp12p1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_e2f6-dp12p1))
:effect (and ( chosen_e2f6-dp12p1) ( num-subs_l2) ( not(not-chosen_e2f6-dp12p1)) ( not(num-subs_l1)))
)
(:action choose_ge2_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_ge2))
:effect (and ( chosen_ge2) ( num-subs_l2) ( not(not-chosen_ge2)) ( not(num-subs_l1)))
)
(:action choose_gp_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_gp))
:effect (and ( chosen_gp) ( num-subs_l2) ( not(not-chosen_gp)) ( not(num-subs_l1)))
)
(:action choose_hdac1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_hdac1))
:effect (and ( chosen_hdac1) ( num-subs_l2) ( not(not-chosen_hdac1)) ( not(num-subs_l1)))
)
(:action choose_hdac1-p130-e2f4p1-dp12_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_hdac1-p130-e2f4p1-dp12))
:effect (and ( chosen_hdac1-p130-e2f4p1-dp12) ( num-subs_l2) ( not(not-chosen_hdac1-p130-e2f4p1-dp12)) ( not(num-subs_l1)))
)
(:action choose_m1433_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_m1433))
:effect (and ( chosen_m1433) ( num-subs_l2) ( not(not-chosen_m1433)) ( not(num-subs_l1)))
)
(:action choose_pcna_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_pcna))
:effect (and ( chosen_pcna) ( num-subs_l2) ( not(not-chosen_pcna)) ( not(num-subs_l1)))
)
(:action choose_prb-e2f4p1-dp12_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_prb-e2f4p1-dp12))
:effect (and ( chosen_prb-e2f4p1-dp12) ( num-subs_l2) ( not(not-chosen_prb-e2f4p1-dp12)) ( not(num-subs_l1)))
)
(:action choose_prbp1-e2f4p1-dp12_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_prbp1-e2f4p1-dp12))
:effect (and ( chosen_prbp1-e2f4p1-dp12) ( num-subs_l2) ( not(not-chosen_prbp1-e2f4p1-dp12)) ( not(num-subs_l1)))
)
(:action choose_prbp2_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_prbp2))
:effect (and ( chosen_prbp2) ( num-subs_l2) ( not(not-chosen_prbp2)) ( not(num-subs_l1)))
)
(:action choose_rpa_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_rpa))
:effect (and ( chosen_rpa) ( num-subs_l2) ( not(not-chosen_rpa)) ( not(num-subs_l1)))
)
(:action choose_sp1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_sp1))
:effect (and ( chosen_sp1) ( num-subs_l2) ( not(not-chosen_sp1)) ( not(num-subs_l1)))
)
(:action choose_wee1_l2_l1
:parameters ()
:precondition (and ( num-subs_l1) ( not-chosen_wee1))
:effect (and ( chosen_wee1) ( num-subs_l2) ( not(not-chosen_wee1)) ( not(num-subs_l1)))
)
(:action dummy-action-4-2
:parameters ()
:precondition  ( available_cycep1)
:effect  ( goal4_)
)
(:action dummy-action-2-2
:parameters ()
:precondition  ( available_p107)
:effect  ( goal2_)
)
(:action dummy-action-1-2
:parameters ()
:precondition  ( available_pol)
:effect  ( goal1_)
)
(:action synthesize_cebp-gp_p
:parameters ()
:precondition  ( available_cebp-gp)
:effect  ( available_p)
)
(:action synthesize_sp1-e2f13-gp_c-myc
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_c-myc)
)
(:action synthesize_sp1-e2f13-gp_cyca
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_cyca)
)
(:action synthesize_sp1-e2f13-gp_cycd
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_cycd)
)
(:action synthesize_sp1-e2f13-gp_cycdp1
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_cycdp1)
)
(:action synthesize_sp1-e2f13-gp_cyce
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_cyce)
)
(:action synthesize_sp1-e2f13-gp_cycep1
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_cycep1)
)
(:action synthesize_sp1-e2f13-gp_p107
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_p107)
)
(:action synthesize_sp1-e2f13-gp_p107p1
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_p107p1)
)
(:action synthesize_sp1-e2f13-gp_p19arf
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_p19arf)
)
(:action synthesize_sp1-e2f13-gp_pol
:parameters ()
:precondition  ( available_sp1-e2f13-gp)
:effect  ( available_pol)
)
(:action synthesize_sp1-gp_c-myc
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_c-myc)
)
(:action synthesize_sp1-gp_cyca
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_cyca)
)
(:action synthesize_sp1-gp_cycd
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_cycd)
)
(:action synthesize_sp1-gp_cycdp1
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_cycdp1)
)
(:action synthesize_sp1-gp_cyce
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_cyce)
)
(:action synthesize_sp1-gp_cycep1
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_cycep1)
)
(:action synthesize_sp1-gp_p107
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_p107)
)
(:action synthesize_sp1-gp_p107p1
:parameters ()
:precondition  ( available_sp1-gp)
:effect  ( available_p107p1)
)
(:action synthesize_sp1-gp_p19arf
:parameters ()
:precondition  ( available_sp1-gp)
:effect (and ( available_p19arf) ( r7))
)
(:action synthesize_sp1-gp_pol
:parameters ()
:precondition  ( available_sp1-gp)
:effect (and ( available_pol) ( r6))
)
(:action associate-with-catalyze_cdc25c_c-tak1_cdc25cp2
:parameters ()
:precondition (and ( available_c-tak1) ( available_cdc25c))
:effect (and ( available_cdc25cp2) ( not(available_cdc25c)))
)
(:action associate_c-abl_prbp2_c-abl-prbp2
:parameters ()
:precondition (and ( available_prbp2) ( available_c-abl))
:effect (and ( available_c-abl-prbp2) ( not(available_c-abl)) ( not(available_prbp2)))
)
(:action associate_cebp_gp_cebp-gp
:parameters ()
:precondition (and ( available_gp) ( available_cebp))
:effect (and ( available_cebp-gp) ( not(available_cebp)) ( not(available_gp)))
)
(:action associate_cebp_prbp2_cebp-prbp2
:parameters ()
:precondition (and ( available_prbp2) ( available_cebp))
:effect (and ( available_cebp-prbp2) ( not(available_cebp)) ( not(available_prbp2)))
)
(:action associate_e2f6-dp12p1_ge2_e2f6-dp12p1-ge2
:parameters ()
:precondition (and ( available_ge2) ( available_e2f6-dp12p1))
:effect (and ( available_e2f6-dp12p1-ge2) ( r5) ( not(available_e2f6-dp12p1)) ( not(available_ge2)))
)
(:action associate_hdac1-p130-e2f4p1-dp12_ge2_hdac1-p130-e2f4p1-dp12-ge2
:parameters ()
:precondition (and ( available_ge2) ( available_hdac1-p130-e2f4p1-dp12))
:effect (and ( available_hdac1-p130-e2f4p1-dp12-ge2) ( not(available_hdac1-p130-e2f4p1-dp12)) ( not(available_ge2)))
)
(:action associate_hdac1_prb-e2f4p1-dp12_hdac1-prb-e2f4p1-dp12
:parameters ()
:precondition (and ( available_prb-e2f4p1-dp12) ( available_hdac1))
:effect (and ( available_hdac1-prb-e2f4p1-dp12) ( not(available_hdac1)) ( not(available_prb-e2f4p1-dp12)))
)
(:action associate_prb-e2f4p1-dp12_ge2_prb-e2f4p1-dp12-ge2
:parameters ()
:precondition (and ( available_ge2) ( available_prb-e2f4p1-dp12))
:effect (and ( available_prb-e2f4p1-dp12-ge2) ( not(available_prb-e2f4p1-dp12)) ( not(available_ge2)))
)
(:action associate_prbp1-e2f4p1-dp12_ge2_prbp1-e2f4p1-dp12-ge2
:parameters ()
:precondition (and ( available_ge2) ( available_prbp1-e2f4p1-dp12))
:effect (and ( available_prbp1-e2f4p1-dp12-ge2) ( not(available_prbp1-e2f4p1-dp12)) ( not(available_ge2)))
)
(:action associate_sp1-e2f13_gp_sp1-e2f13-gp
:parameters ()
:precondition (and ( available_gp) ( available_sp1-e2f13))
:effect (and ( available_sp1-e2f13-gp) ( not(available_sp1-e2f13)) ( not(available_gp)))
)
(:action associate_sp1_e2f13_sp1-e2f13
:parameters ()
:precondition (and ( available_e2f13) ( available_sp1))
:effect (and ( available_sp1-e2f13) ( not(available_sp1)) ( not(available_e2f13)))
)
(:action associate_sp1_gp_sp1-gp
:parameters ()
:precondition (and ( available_gp) ( available_sp1))
:effect (and ( available_sp1-gp) ( not(available_sp1)) ( not(available_gp)))
)
(:action initialize_c-abl
:parameters ()
:precondition  ( chosen_c-abl)
:effect  ( available_c-abl)
)
(:action initialize_cdc25c
:parameters ()
:precondition  ( chosen_cdc25c)
:effect  ( available_cdc25c)
)
(:action initialize_cdk2
:parameters ()
:precondition  ( chosen_cdk2)
:effect  ( available_cdk2)
)
(:action initialize_cdk2p1
:parameters ()
:precondition  ( chosen_cdk2p1)
:effect  ( available_cdk2p1)
)
(:action initialize_cebp
:parameters ()
:precondition  ( chosen_cebp)
:effect  ( available_cebp)
)
(:action initialize_c-tak1
:parameters ()
:precondition  ( chosen_c-tak1)
:effect  ( available_c-tak1)
)
(:action initialize_dmp1
:parameters ()
:precondition  ( chosen_dmp1)
:effect  ( available_dmp1)
)
(:action initialize_e2f13
:parameters ()
:precondition  ( chosen_e2f13)
:effect  ( available_e2f13)
)
(:action initialize_e2f4-dp12p1
:parameters ()
:precondition  ( chosen_e2f4-dp12p1)
:effect  ( available_e2f4-dp12p1)
)
(:action initialize_e2f6-dp12p1
:parameters ()
:precondition  ( chosen_e2f6-dp12p1)
:effect  ( available_e2f6-dp12p1)
)
(:action initialize_ge2
:parameters ()
:precondition  ( chosen_ge2)
:effect  ( available_ge2)
)
(:action initialize_gp
:parameters ()
:precondition  ( chosen_gp)
:effect  ( available_gp)
)
(:action initialize_hdac1
:parameters ()
:precondition  ( chosen_hdac1)
:effect  ( available_hdac1)
)
(:action initialize_hdac1-p130-e2f4p1-dp12
:parameters ()
:precondition  ( chosen_hdac1-p130-e2f4p1-dp12)
:effect  ( available_hdac1-p130-e2f4p1-dp12)
)
(:action initialize_m1433
:parameters ()
:precondition  ( chosen_m1433)
:effect  ( available_m1433)
)
(:action initialize_pcna
:parameters ()
:precondition  ( chosen_pcna)
:effect  ( available_pcna)
)
(:action initialize_prb-e2f4p1-dp12
:parameters ()
:precondition  ( chosen_prb-e2f4p1-dp12)
:effect  ( available_prb-e2f4p1-dp12)
)
(:action initialize_prbp1-e2f4p1-dp12
:parameters ()
:precondition  ( chosen_prbp1-e2f4p1-dp12)
:effect  ( available_prbp1-e2f4p1-dp12)
)
(:action initialize_prbp2
:parameters ()
:precondition  ( chosen_prbp2)
:effect  ( available_prbp2)
)
(:action initialize_rpa
:parameters ()
:precondition  ( chosen_rpa)
:effect  ( available_rpa)
)
(:action initialize_sp1
:parameters ()
:precondition  ( chosen_sp1)
:effect  ( available_sp1)
)
(:action initialize_wee1
:parameters ()
:precondition  ( chosen_wee1)
:effect  ( available_wee1)
)
(:action choose_c-abl_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_c-abl))
:effect (and ( chosen_c-abl) ( num-subs_l1) ( not(not-chosen_c-abl)) ( not(num-subs_l0)))
)
(:action choose_cdc25c_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdc25c))
:effect (and ( chosen_cdc25c) ( num-subs_l1) ( not(not-chosen_cdc25c)) ( not(num-subs_l0)))
)
(:action choose_cdk2_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdk2))
:effect (and ( chosen_cdk2) ( num-subs_l1) ( not(not-chosen_cdk2)) ( not(num-subs_l0)))
)
(:action choose_cdk2p1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cdk2p1))
:effect (and ( chosen_cdk2p1) ( num-subs_l1) ( not(not-chosen_cdk2p1)) ( not(num-subs_l0)))
)
(:action choose_cebp_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_cebp))
:effect (and ( chosen_cebp) ( num-subs_l1) ( not(not-chosen_cebp)) ( not(num-subs_l0)))
)
(:action choose_c-tak1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_c-tak1))
:effect (and ( chosen_c-tak1) ( num-subs_l1) ( not(not-chosen_c-tak1)) ( not(num-subs_l0)))
)
(:action choose_dmp1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_dmp1))
:effect (and ( chosen_dmp1) ( num-subs_l1) ( not(not-chosen_dmp1)) ( not(num-subs_l0)))
)
(:action choose_e2f13_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_e2f13))
:effect (and ( chosen_e2f13) ( num-subs_l1) ( not(not-chosen_e2f13)) ( not(num-subs_l0)))
)
(:action choose_e2f4-dp12p1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_e2f4-dp12p1))
:effect (and ( chosen_e2f4-dp12p1) ( num-subs_l1) ( not(not-chosen_e2f4-dp12p1)) ( not(num-subs_l0)))
)
(:action choose_e2f6-dp12p1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_e2f6-dp12p1))
:effect (and ( chosen_e2f6-dp12p1) ( num-subs_l1) ( not(not-chosen_e2f6-dp12p1)) ( not(num-subs_l0)))
)
(:action choose_ge2_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_ge2))
:effect (and ( chosen_ge2) ( num-subs_l1) ( not(not-chosen_ge2)) ( not(num-subs_l0)))
)
(:action choose_gp_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_gp))
:effect (and ( chosen_gp) ( num-subs_l1) ( not(not-chosen_gp)) ( not(num-subs_l0)))
)
(:action choose_hdac1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_hdac1))
:effect (and ( chosen_hdac1) ( num-subs_l1) ( not(not-chosen_hdac1)) ( not(num-subs_l0)))
)
(:action choose_hdac1-p130-e2f4p1-dp12_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_hdac1-p130-e2f4p1-dp12))
:effect (and ( chosen_hdac1-p130-e2f4p1-dp12) ( num-subs_l1) ( not(not-chosen_hdac1-p130-e2f4p1-dp12)) ( not(num-subs_l0)))
)
(:action choose_m1433_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_m1433))
:effect (and ( chosen_m1433) ( num-subs_l1) ( not(not-chosen_m1433)) ( not(num-subs_l0)))
)
(:action choose_pcna_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_pcna))
:effect (and ( chosen_pcna) ( num-subs_l1) ( not(not-chosen_pcna)) ( not(num-subs_l0)))
)
(:action choose_prb-e2f4p1-dp12_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_prb-e2f4p1-dp12))
:effect (and ( chosen_prb-e2f4p1-dp12) ( num-subs_l1) ( not(not-chosen_prb-e2f4p1-dp12)) ( not(num-subs_l0)))
)
(:action choose_prbp1-e2f4p1-dp12_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_prbp1-e2f4p1-dp12))
:effect (and ( chosen_prbp1-e2f4p1-dp12) ( num-subs_l1) ( not(not-chosen_prbp1-e2f4p1-dp12)) ( not(num-subs_l0)))
)
(:action choose_prbp2_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_prbp2))
:effect (and ( chosen_prbp2) ( num-subs_l1) ( not(not-chosen_prbp2)) ( not(num-subs_l0)))
)
(:action choose_rpa_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_rpa))
:effect (and ( chosen_rpa) ( num-subs_l1) ( not(not-chosen_rpa)) ( not(num-subs_l0)))
)
(:action choose_sp1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_sp1))
:effect (and ( chosen_sp1) ( num-subs_l1) ( not(not-chosen_sp1)) ( not(num-subs_l0)))
)
(:action choose_wee1_l1_l0
:parameters ()
:precondition (and ( num-subs_l0) ( not-chosen_wee1))
:effect (and ( chosen_wee1) ( num-subs_l1) ( not(not-chosen_wee1)) ( not(num-subs_l0)))
)

)
